### ISSUE TITLE
Code 500 error

### ISSUE THREAD

**Issue by infzxz** [chriskyfung/AutoFetcher-IG-Stories-to-GDrive#10]
Exception: Request failed for https://www.instagram.com returned code 500. Truncated server response: {"message": "execution failure", "errors": [{"message": "execution error", "locations": []}], "data": {"reels_media": null}, "status": "fail"} (use muteHttpExceptions option to examine full response) (line 22, file "Code")

What's going wrong?

**Comment by infzxz** [comment]
More:

Exception: Request failed for https://www.instagram.com returned code 500. Truncated server response: {"message": "execution failure", "errors": [{"message": "execution error", "locations": []}], "data": {"reels_media": null}, "status": "fail"} (use muteHttpExceptions option to examine full response)
    at fetch_ig_stories(Code:23:22)
    at myFunction(Code:68:14)
    at doGet(Code:207:11)

**Comment by infzxz** [comment]
When auto-running via trigger (new function is called `autor`):

	ReferenceError: uploadToDrive is not defined
    at myFunction(Code:86:9)
    at doGet(Code:207:11)
    at autor(Code:238:3)

**Comment by chriskyfung** [comment]
The function uploadToDrive is in the script file 👉
[url_to_drive.gs](https://www.github.com/chriskyfung/AutoFetcher-IG-Stories-to-GDrive/tree/master/gascript%2Furl_to_drive.gs)

I guess the `autor` function is something from Google. You don't need to bother it.

**Comment by infzxz** [comment]
`autor` was my renamed `try_get`

The auto-run works now 👍

I still get code 500 when testing with:
`https://script.google.com/<my-app-path>/exec?usr=username&pwd=password&target={"target":{"name":"nasa","id":"528817151"}}`

But it doesn't matter if autorun is working.

**Comment by chriskyfung** [comment]
Sorry for your inconvenience! The problem was due to a bug within the function `doGet()`.
I execute the script via setting time triggers rather than calling the deployment endpoint.
Therefore, I forgot to update `doGet()` with `JSON.parse()`.

I'd corrected the issue. Please try the latest version and pass a query string like below:
`https://script.google.com/<my-app-path>/exec?usr=username&pwd=password&target={"name":"nasa","id":"528817151"}`

**Comment by infzxz** [comment]
New error:

```
SyntaxError: Unexpected token < in JSON at position 1
    at parseDownloadUrl(Code:42:21)
    at myFunction(Code:72:14)
    at doGet(Code:210:11)
```

**Comment by infzxz** [comment]
After changing code I needed a new `query_hash` and `COOKIE`

All good now!

**Comment by infzxz** [comment]
Oops.
Works through the URL `https://script.google.com/<my-app-path>/exec?usr=username&pwd=password&target={"name":"nasa","id":"528817151"}`

But now, auto-run does not work. Says "completed" but it does not save story:

```
Stackdriver logs
Nov 7, 2020, 2:40:17 PM	Info	SyntaxError: Unexpected token o in JSON at position 1
Nov 7, 2020, 2:40:17 PM	Info	TextOutput
```

**Comment by chriskyfung** [comment]
No story on Nasa's Instagram in the last 24 hours.

Please test with another one!

**Comment by infzxz** [comment]
Same problem with bbcnews:
Works through url:
`https://script.google.com/<my-app-path>/exec?usr=username&pwd=password&target={"name":"bbcnews","id":"16278726"}`

auto-run does not work:
```
Stackdriver logs
Nov 7, 2020, 3:23:00 PM	Info	SyntaxError: Unexpected token o in JSON at position 1
Nov 7, 2020, 3:23:00 PM	Info	TextOutput
```

**Comment by chriskyfung** [comment]
Supposing that you know how to change JSON to string in the `try_get()`, you can simply fix the issue without an extra piece of code.

By the way, I explicitly added a conditional check to accept both JSON and string values for the `target` param.
Please test the latest commit.

**Comment by infzxz** [comment]
Tried the latest commit and both are working now, thanks!
