### ISSUE TITLE
Instagram now locks accounts very soon

### ISSUE THREAD

**Issue by royjor2016** [chriskyfung/AutoFetcher-IG-Stories-to-GDrive#14]
After resolving issue #11 at around Dec 8, 2020, 10:41:02 PM, my account was locked for the first time at Dec 9, 2020, 3:42:05 AM .

error log

> Exception: Request failed for https://i.instagram.com returned code 400. Truncated server response: {"message": "checkpoint_required", "checkpoint_url": "https://i.instagram.com/challenge/?next=/api/v1/feed/reels_media/%253Freel_ids%253Dxxxxxxxxxxx... (use muteHttpExceptions option to examine full response)
    at fetch_ig_stories(code:47:26)
    at __main__(code:94:14)
    at doGet(code:233:15)
    at xxxxxxxxxx(code:261:3)

they sent me an email. i keyed in the verification code. account was unlocked. i was ordered to change my password.

i thought maybe i was triggering it too frequently, so i lowered the frequency a bit. i got a new set of cookies and  X_IG_WWW_CLAIM, and started running again at Dec 9, 2020, 8:36:36 AM. This time i am using this set to fetch one account every 30 minutes and another account every hour. => 3 fetches in total every hour.

between Dec 12, 2020, 1:48:16 AM and 2:10:05 AM my account is locked again.

> Exception: Request failed for https://i.instagram.com returned code 400. Truncated server response: {"message": "checkpoint_required", "checkpoint_url": "https://i.instagram.com/challenge/?next=/api/v1/feed/reels_media/%253Freel_ids%253Dxxxxxxxxxxx... (use muteHttpExceptions option to examine full response)
    at fetch_ig_stories(code:52:26)
    at __main__(code:104:14)
    at doGet(code:243:15)
    at xxxxxxxxxxx(code:271:3)

this time i am asked to give a phone number. i receive an SMS, put in the code. now they say they are reviewing my account and will unblock it within 24 hours maybe. or maybe lock it out forever.

so this run lasted for almost three days.

before issue #11 i had the script running for a month without any problem.

maybe something could be done on the script side, to avoid getting locked by IG. maybe not. i dont know.

from another website's experience, i have an idea.
what if we use not just one set of cookies and X_IG_WWW_CLAIM, but say 10 sets, and rotate it?
how infrequent should it be to not trigger IG locks?

or could there be another fetching method that would not trigger locks?

**Comment by royjor2016** [comment]
other people are probably reporting similar problems. IG tightened its detection.
https://github.com/postaddictme/instagram-php-scraper/issues/822

**Comment by chriskyfung** [comment]
My IG account is still working well.
I think you fetch too frequently. I only trigger the script every six hours.

**Comment by chriskyfung** [comment]
I didn't observe that the value of `X_IG_WWW_CLAIM` changes very often in my browser. tIn the contrary, the following part of the IG cookie changes every request: `urlgen="{\"000.000.000.000\": 0000}:1ko2qX:xxxxxxxx-xxxxxxx-xxxxxxxxxx"`; where the value beyond `1ko2qX` is unrecognizable from the context.
