### ISSUE TITLE
How to find the values of x-ig-app-id, x-ig-www-claim, and cookie

### ISSUE THREAD

**Issue by viksra** [chriskyfung/AutoFetcher-IG-Stories-to-GDrive#35]
I believe the section titled "How to find the values of x-ig-app-id, x-ig-www-claim, and cookie" is no longer correct. Under "Request Headers", cookie, x-ig-app-id and x-ig-www-claim are not there.

EDIT: I had to play the story all the way through, now it appears.

**Comment by chriskyfung** [comment]
You should be able to find the values of `x-ig-app-id`, `x-ig-www-claim`, and `cookie` using Chrome DevTools as in the README file.
