### ISSUE TITLE
Fails with: "Exception: Attribute provided with invalid value: Header:x-ig-www-claim"

### ISSUE THREAD

**Issue by janmaslo** [chriskyfung/AutoFetcher-IG-Stories-to-GDrive#41]
my x-ig-www-claim starts with "hmac." and has a hyphen in the middle. It's the exact same one I copied from the dev tools

**Comment by chriskyfung** [comment]
Yes, the `x-ig-www-claim` starts with **hmac.** and has a hyphen in the middle.

**Comment by janmaslo** [comment]
So it should be correct and not an `invalid value` as was stated in the error message I received?

**Comment by chriskyfung** [comment]
It seems to be regard to the following issue: https://github.com/googleworkspace/apps-script-oauth2/issues/123

**Comment by fifson1** [comment]
> It seems to be regard to the following issue: [googleworkspace/apps-script-oauth2#123](https://github.com/googleworkspace/apps-script-oauth2/issues/123)

How I can use this to fix error?
