### ISSUE TITLE
跟足步驟照做 但係冇嘢download到嘅？

### ISSUE THREAD

**Issue by royjor2016** [chriskyfung/AutoFetcher-IG-Stories-to-GDrive#7]
Hi 師兄!

我經已按正你 https://chriskyfung.github.io/AutoFetcher-IG-Stories-to-GDrive/ 呢個介紹做，set埋trigger，而且我睇Dashboard嘅「My Executions」已經係run咗好多次，冇error，但係搵唔到任何嘢download咗落Google drive嘅？我嘅target依家係有一個ig story。

我完全搞唔明邊度可能出錯。請問你可唔可以整個video tutorial，演示一次？唔該你先！

**Comment by chriskyfung** [comment]
Please **line 22** in the code.gs with the following:

```js
  var data = UrlFetchApp.fetch(query, opt2).getContentText();
  Logger.log(data);
  return data;
```

Run the **test_pipeline()** then send me the log messages.

**Comment by royjor2016** [comment]
So I replaced line 22 with the block.
Then I clicked "deploy as web app..."
Then I clicked Run -> Run function -> test pipeline

I got a red-background warning saying
_ReferenceError: Drive is not defined (line 184, file "code")_

**Comment by royjor2016** [comment]
my line 184 is
`var updatedFile = Drive.Files.update(file_meta, lastTestedBadge_id,badgeBlob);`

**Comment by chriskyfung** [comment]
The [**Drive**](https://developers.google.com/apps-script/advanced/drive) class is an Advanced Google Services. You need to enable the Drive API from [**Resources** > **Advanced Google services....**](https://developers.google.com/apps-script/guides/services/advanced)

You can omit it by commenting out `updateLastTestedBadge();`, `updateBadgeToFailStatus();` and `updateBadgeToSucessStatus();` within the `test_pipeline()` function (lines 123, 131 and 137 in the original file).

**Comment by royjor2016** [comment]
I turned on the Drive class.

These are logs I got from "My Executions"

> Stackdriver logs
Nov 5, 2020, 8:32:20 AM
Info
{"data":{"reels_media":[]},"status":"ok"}
Nov 5, 2020, 8:32:20 AM
Info
Number of URL(s) from @16278726: 0
Nov 5, 2020, 8:32:20 AM
Info
{"data":{"reels_media":[]},"status":"ok"}
Nov 5, 2020, 8:32:20 AM
Info
Number of URL(s) from @528817151: 0
Nov 5, 2020, 8:32:20 AM
Info
{"data":{"reels_media":[]},"status":"ok"}
Nov 5, 2020, 8:32:20 AM
Info
Number of URL(s) from @1112881921: 0
Nov 5, 2020, 8:32:20 AM
Info
Failed to fetch data from the test accounts!!!

I also tried omitting the lines you said. I guess the logs are roughly the same.

> Stackdriver logs
Nov 5, 2020, 8:32:20 AM
Info
{"data":{"reels_media":[]},"status":"ok"}
Nov 5, 2020, 8:32:20 AM
Info
Number of URL(s) from @16278726: 0
Nov 5, 2020, 8:32:20 AM
Info
{"data":{"reels_media":[]},"status":"ok"}
Nov 5, 2020, 8:32:20 AM
Info
Number of URL(s) from @528817151: 0
Nov 5, 2020, 8:32:20 AM
Info
{"data":{"reels_media":[]},"status":"ok"}
Nov 5, 2020, 8:32:20 AM
Info
Number of URL(s) from @1112881921: 0
Nov 5, 2020, 8:32:20 AM
Info
Failed to fetch data from the test accounts!!!

**Comment by royjor2016** [comment]
Also I checked the logs on the function copied from try_get and renamed.
Before i turn on Drive class there's no logs.
After turning it on, I get this when I or Trigger runs that function

> Stackdriver logs
Nov 4, 2020, 3:32:59 PM
Info
{"data":{"reels_media":[]},"status":"ok"}

**Comment by chriskyfung** [comment]
:( 

There should be something in "reels_media":[{"__typename":"GraphReel","id":"16278726","latest_reel_media":1604575351,"can_reply":true,"owner":{"__typename":"GraphUser","id":"16278726","profile_pic_url":"https://sconte..."

I guess you may have a wrong cookie

**Comment by royjor2016** [comment]
唔該晒師兄！換咗個account又換咗個browser攞咗新嘅cookie，就得咗。原先我用firefox，後來用chrome，但係兩個ig account唔同。結果個query hash好似係一樣？！

唔知舊cookie咩事。唯二變量係browser同account，所以唔知關邊樣事啦。

再一次唔該晒你先！ thx a lot! great help!
