### ISSUE TITLE
Destination folder ID seems not to work

### ISSUE THREAD

**Issue by AndrewSB** [chriskyfung/AutoFetcher-IG-Stories-to-GDrive#71]
Hey! i've tried entering in a destination folder ID, but every execution uses the root folder instead. i see the relevant code has been implemented (where it does `.folderWithId(destinationFolderID) ?? .rootFolder`

but does that not work? i'm using v6 of the script

**Comment by AndrewSB** [comment]
i do see in the sheet the column says "Pending implementation"

**Comment by cheyq99** [comment]
> 

with v6 Destination Folder ID comment 'Pending Feature'

**Comment by AndrewSB** [comment]
got it. i'd love an update on this issue once it's ready. 

appreciate your work!

**Comment by chriskyfung** [comment]
Same as #20
