### ISSUE TITLE
8 April 2023 breakdown: Request failed for https://i.instagram.com returned code 400...

### ISSUE THREAD

**Issue by royjor2016** [chriskyfung/AutoFetcher-IG-Stories-to-GDrive#76]
**Describe the bug**

it appears instagram just broke something again.

i've been using your script from 3 years ago and changing cookies, ids, etc., once in a while. it broke around 1 april a few times, i changed the cookies again. 7 april it broke again. i just tried updating the cookies data, it couldnt work.

i installed the newest version (Copy of [v8] IG-Stories-AutoFetcher (for build2023.02.16)) by clicking the green button. here's what i get. tried it with bbcnews or my personal subscribed account, both failed similarly.

```
Apr 8, 2023, :47:12 PM
Error
Request failed for https://i.instagram.com returned code 400. Truncated server response: <html>
<head>
<title>5xx Server Error</title>
</head>

<body>
<h1>5xx Server Error</h1>
</body>

</html>
 (use muteHttpExceptions option to examine full response). (error code: 0xf1)
Apr 8, 2023, :47:12 PM
Error
Error: Request failed for https://i.instagram.com returned code 400. Truncated server response: <html>
<head>
<title>5xx Server Error</title>
</head>

<body>
<h1>5xx Server Error</h1>
</body>

</html>
 (use muteHttpExceptions option to examine full response). (error code: 0xf1)
    at getInstagramData(bundle:508:11)
    at fetch(bundle:574:16)
    at [unknown function](bundle:747:17)
    at batchFetch(bundle:745:8)
    at run(code:3:8)
```

i'd like to take this opportunity to thank you guys too. the script has been amazing!

**Comment by royjor2016** [comment]
i'm using firefox 111.0.1 (64-bit) on win10. i've already tried forgetting instagram.com (clearing caches, history, everything about it) and then used the new cookies after logging in.

**Comment by royjor2016** [comment]
i used details from a different account on chrome but same computer. now both the old and new scripts work again. i dont know if there's something wrong with my usual fetcher account or firefox.

**Comment by chriskyfung** [comment]
Please browse and copy the Cookies from Chrome
