### ISSUE TITLE
Logs date time should write UTC

### ISSUE THREAD

**Issue by royjor2016** [chriskyfung/AutoFetcher-IG-Stories-to-GDrive#77]
current format
Date time
11/04/2023, 16:28:41

proposed format
Date time
2023-04-11, 08:28:41 (UTC)
(something like this, using iso date yyyy-mm-dd and specifying utc)

reason
not every one lives in UTC+8.

**Comment by chriskyfung** [comment]
Hi @royjor2016,

You can simply change the time zone from the Script Editor by following these steps:

1. Open your Google Sheet file in a browser.
2. Select **Tools > Script Editor** from the menu of the Sheets UI,
3. In the Script Editor, click **Project Settings** ⚙ at the left.
4. Choose your preferred time zone from the dropdown under the **General settings**.

![image](https://user-images.githubusercontent.com/8746768/233823013-d32fc2bb-0b9b-44c9-a438-1dab710e059b.png)

The script will format the date with the new time zone setting in future executions.

**Comment by chriskyfung** [comment]
See #80
