### ISSUE TITLE
Standardise log date and time format!!!

### ISSUE THREAD

**Issue by royjor2016** [chriskyfung/AutoFetcher-IG-Stories-to-GDrive#80]
**Describe the bug**
Copied from my spreadsheet

> 4/5/2023, 下午03:52:42
> 5/4/2023, 上午06:34:07

it has to be standardised! "4/5/2023, 下午03:52:42" was a log produced by manually clicking the "run" button in the sheet. "5/4/2023, 上午06:34:07" was from the daily trigger.

i believe #78 would solve at least part of the problem. othewise, please debug! either use iso format or write it out in full english names like 4 May 2023!

**Comment by chriskyfung** [comment]
Change the locale in your Apps Script setting.

**Comment by chriskyfung** [comment]
Both ways trigger the same code, the values should have the same format.

Please try the following:

1. Open your Google Sheet, select **File > Settings**. Change the **Locale** and **Time Zone**, then click **Save and reload**.

2. Select the column A (Date time) on the _Logs_ spreadsheet.

3. Choose **Format > Number > Date time** or **Custom date and time** to modify the data format of the column and existing date time values.

**Comment by royjor2016** [comment]
@chriskyfung the dates dont match

6/21/2023, 9:07:43 AM
6/20/2023, 9:07:42 AM
19/06/2023, 21:12:39
19/06/2023, 21:12:34

this is what i got. i made a fresh copy last week and set the "settings" under "file" in google sheet to gmt-0 and usa,
manually running it gets 19/06/2023. triggers get 6/21/2023.

beforehand i have also tried setting the column's format to what i wish it to be. it also wont standardise.

**Comment by royjor2016** [comment]
@chriskyfung 

here're the dates i just got:

03/07/2023, 03:00:24
03/07/2023, 03:00:19
07/02/2023, 22:52:42
07/02/2023, 22:52:36

these timestamps are actually gmt+8. "03/07" (day before month) were logs from manually clicking run button in google sheet. "07/02" are trigger run logs.

here's what i had done:

1. made a new copy of the script by clicking the button on your readme documentation.
2. File -> Settings -> set to english (uk) and gmt+0 no daylight saving.

with these settings i get those messy logs.

**Comment by royjor2016** [comment]
@chriskyfung can you please hardcode the timestamp format to include the timezone and standardise months and days. it doest have to be iso 8601. it just needs to be clear and not confusing.

**it's super annoying to have messy logs and have to guess the timezone.**

**Comment by chriskyfung** [comment]
1. I didn't reproduce your reported issue.
2. I don't think the date is an important feature as it is just a log file. People want the media files not the date. Besides, you can still find the correct datetime in your system timezone from the list view or file detail on the right pane on Google Drive.
3. This project is free and open source, its developer is not responsible for meeting individual needs. If the date is ready essential to you, fork this repository and change the code by yourself. Submit a merge request to contribute the project. We will  review your work and consider if it can be merged to the production branck.

**Comment by chriskyfung** [comment]
@royjor2016 

1. I didn't reproduce your reported issue.
2. I don't think the date is an important feature as it is just a log file. People want the media files not the date. Besides, you can still find the correct datetime in your system timezone from the list view or file detail on the right pane on Google Drive.
3. This project is free and open source, its developer is not responsible for meeting individual needs. If the date is ready essential to you, fork this repository and change the code by yourself. Submit a merge request to contribute the project. We will  review your work and consider if it can be merged to the production branch.
