### ISSUE TITLE
Error code 401

### ISSUE THREAD

**Issue by junyaducard** [chriskyfung/AutoFetcher-IG-Stories-to-GDrive#83]
Hi Chris,

Thank you for the App. I keep getting error code 401 (server response: {"message":"請幾分鐘後再試一次。","require_login":true,"status":"fail"}). How can I fix this? Thank you

Best
JD

**Comment by chriskyfung** [comment]
Hi JD, 
Make sure that the login session keeps valid by visiting your IG account daily in a Chrome browser :)
For more details, please refer to Issue #45 .
